permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Jingping Yi
  email: jingping.yi@gmail.com
  link: https://yijingping.github.io/
  weibo: http://weibo.com/u/1708225792
  github: http://github.com/yijingping
  music: https://www.douban.com/people/yijingping/
  linkedin: http://www.linkedin.com/in/jingping-yi-5ab45572

# 站点信息
title: 易先生の世界
description: My personal blog
url: https://yijingping.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/avatar.jpg
favicon: /public/img/avatar.jpg

# google analytics 设置
ga:
  id: UA-45927312-1
  url: yijingping.github.io

# disqus 设置
disqus:
  shortname: yijingping

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates:
  - 思考

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档